### ISSUE TITLE
Search for path on caret or cursor positions?

### ISSUE THREAD

**Issue by halfbrained** [halfbrained/cuda_embed_ed#1]
@Alexey-T

Currently plugin searches for path on caret position. Maybe it should be cursor? Or give an option?

**Comment by Alexey-T** [comment]
> Maybe it should be cursor?

mouse cursor? you can get it's move via event on_mouse_stop.
what is better- IDK...

**Comment by halfbrained** [comment]
Ok, will leave as is until someone complains :)
