### ISSUE TITLE
how to use API?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_embed_ed#10]
![Screenshot from 2021-06-13 23-41-09](https://user-images.githubusercontent.com/4154978/121821304-e2fd0b00-cca0-11eb-974b-ea2f205da43b.png)

**Comment by halfbrained** [comment]
``` python
open_file_embedded(filepath, nline, caption=None)
```
`filepath` - absolute path to a document to be opened, should exist
`nline` - line index, should not be greater than number of lines in current document
`caption` - optional, will be shown instead of full path if provided

**Comment by Alexey-T** [comment]
My API call gave a crash-- picture shown in 1st post... why?

**Comment by halfbrained** [comment]
you are trying to show embedded editor after line **13**, in a **8** line document

This should work:
``` python
open_file_embedded('/home/user/torrent.cpp', 5)
```

**Comment by Alexey-T** [comment]
pls don't crash on 'bad' line index!
and note: Cud API allows the gap before first line - lineindex must be -1.

you can read ed.get_line_count()

**Comment by halfbrained** [comment]
I now clamp line index to the document's range. Also added a bit of [argument validation](https://github.com/halfbrained/cuda_embed_ed/commit/ff1f78e1f3d03235ce1f16221bd1f64bd1b2baed#diff-2c5351923a8e51828e03b3f66520f907b2dc75b86168518204c9764528788598R39-R53)
