### ISSUE TITLE
paths with / and \ separators both must work on Unix/Windows (at least for Pascal, Pascal needs it)

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_embed_ed#12]

**Comment by halfbrained** [comment]
Windows doesn't caret what the separator is in the path, but on linux backslash can be part of file's name... so I'm hesitant to just replace backslash with a slash. 

Would it be best to just check both path variants on unixes -- if file exists? Chances of this causing trouble seem astronomically low

**Comment by Alexey-T** [comment]
>to just check both path variants on unixes -- if file exists? 

yes

**Comment by halfbrained** [comment]
Changed
