### ISSUE TITLE
maybe use uniq tag value for gaps, if you use some fixed tag value?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_embed_ed#13]
PROC_GET_UNIQUE_TAG: Gets integer value, which is unique for the current CudaText process (it starts with 100, increasing with each call). Use this value for Editor.markers() and Editor.attr() tag values.

**Comment by halfbrained** [comment]
Already using it :)

``` python
GAP_TAG = app_proc(PROC_GET_UNIQUE_TAG, '')
```
