### ISSUE TITLE
Respect file encoding in Embedded Editor

### ISSUE THREAD

**Issue by de77** [halfbrained/cuda_embed_ed#18]
I have some files that used encoding different from 'utf-8'. When I trying to see them in window of embedded editor pluging I got message:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 185: invalid start byte
ERROR: Exception in CudaText for toggle: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 185: invalid start byte 

Can you consider to do changes for respecting file encoding in Embedded Editor. See attached patch.

```
diff --git a/embed_ed.py b/embed_ed.py
index cc9d2fd..3547650 100644
--- a/embed_ed.py
+++ b/embed_ed.py
@@ -385,7 +385,7 @@ class Hint:
         if self.h is None:
             self.h, self.ed = self.init_form()
 
-        with open(full_path, 'r', encoding='utf-8') as f:
+        with open(full_path, 'r', encoding=ed.get_prop(PROP_ENC, '')) as f:
             text = f.read()
 
         self.full_path = full_path
```

**Comment by Alexey-T** [comment]
If @halfbrained is busy (seems so), I will apply this in my fork. Tkx

**Comment by Alexey-T** [comment]
I will do this-

1. Try to open as utf8 
2. If 1 gives exception, try to load in the same encoding (like patch); if it's not utf8 
3. If 2 gives exception, load as US ASCII

**Comment by Alexey-T** [comment]
Plugin is updated (addons manager), please test.

**Comment by de77** [comment]
Thanks, new version works fine.
