### ISSUE TITLE
Content of included file doesn't showed.

### ISSUE THREAD

**Issue by de77** [halfbrained/cuda_embed_ed#19]
I'm not sure is it issue of cuda_embed_ed or of cudatext itself.

When I press "Plugins -> Embedded Editor -> Toggle" content of included file is not shown, only controls "To new tab", name of included file, "Save" and "Close" is displayed. See attached image. 

May be there is some incompability appeared, because I'm running Cudatext in Windows XP environment with Python 3.4. When I tested in Windows 7 there is all showed ok.

![q](https://user-images.githubusercontent.com/31433412/146507552-dacb529b-a970-4c47-bc2d-3792a395051d.JPG)

@Alexey-T can you help?

**Comment by Alexey-T** [comment]
Please, give me the outer file, and included inner file. Attach in zip.

For what text position do you call embedded? EDIT- I see it, for the line 1

**Comment by Alexey-T** [comment]
2) The same files are working ok on Win7??? Then it must be python 3.4 issue. I don't have the PC with WinXP... :(

**Comment by Alexey-T** [comment]
Your screenshot -- you have 1 console error, what error?

**Comment by de77** [comment]
Done, see attachment.
[q.zip](https://github.com/halfbrained/cuda_embed_ed/files/7734404/q.zip)

PS: the text is:
```
ERROR: CudaText cannot save configs if it's copied to "Program Files" folder
```

**Comment by Alexey-T** [comment]
1) Move Cud out of the "Program Files" folder to eg c:\cudatext
2) I have stable repro (Win10, Cud x32, Py 3.4) of bug

**Comment by de77** [comment]
I moved Cudatext out of "Program Files" and launched by absolute path - D:\cudatext\cudatext.exe q.c  and got same behavior (I mean in that case bug still persists and content of included file is not displayed).

**Comment by Alexey-T** [comment]
Found a bug in Cud 32 bit! Api returns Prop_cell_size wrong

**Comment by Alexey-T** [comment]
Cud release is fixed/updated.

**Comment by Alexey-T** [comment]
Pls close the issue, if solved.

**Comment by de77** [comment]
Thanks, now it works correct.
