### ISSUE TITLE
config file- change to settings/plugins.ini maybe?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_embed_ed#4]
to
```
[embedded_editor]
editor_max_lines=24
```

**Comment by halfbrained** [comment]
Are you sure? I didn't want to do that since it can be quite crowded in plugins.ini - mine is 50 lines :)

**Comment by Alexey-T** [comment]
1-3 lines config file is not ok, let's put it to plugins.ini

**Comment by halfbrained** [comment]
changed
