### ISSUE TITLE
support Pascal

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_embed_ed#6]
if lexer name contains "Pascal" (case insens) then search for this pattern

    {$I dir/filename.ext}

`$I` can be `$i` too.
`/` can be `\` too on win32.

maybe add an option "pascal_lexer_names=" to comma separated lex names.

**Comment by halfbrained** [comment]
Good idea. 

I'll add a generic solution, something like:
``` json
{
  "Pascal": {
    "lexers": ["Pascal"],
    "path_pattern": <regex>
  }
}
```

Will add some default values, and user would be able to add custom ones. Good?

**Comment by Alexey-T** [comment]
Yes, good!

**Comment by halfbrained** [comment]
Added (https://github.com/halfbrained/cuda_embed_ed/commit/eef8b7476f4260d5fab01443ec098b6fb8afd683) Please check if pascal paths work ok
