### ISSUE TITLE
option "show line numbers in embedded editor" will be good

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_embed_ed#8]

**Comment by Alexey-T** [comment]
PROP_GUTTER_ALL: bool: gutter (container for all gutter columns) is visible.
PROP_GUTTER_STATES: bool: show gutter column "line states".
PROP_GUTTER_NUM: bool: show gutter column "line numbers".
PROP_GUTTER_FOLD: bool: show gutter column "folding".
PROP_GUTTER_BM: bool: show gutter column "bookmarks".

**Comment by halfbrained** [comment]
ok, I will take other values from app options for target document, and have a separate plugin option for line numbers.

**Comment by halfbrained** [comment]
Added (427d9d2f0d1674560b42fc2a121e4c7dda8f3536)
``` markdown
* show_line_num - show line numbers; possible values:
	0 - hide
	1 - show
	2 - use CudaText settings (default)
```
