### ISSUE TITLE
I suggest this new readme

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_embed_ed#9]
[readme.txt](https://github.com/halfbrained/cuda_embed_ed/files/6643976/readme.txt)

**Comment by Alexey-T** [comment]
Updated
[readme.txt](https://github.com/halfbrained/cuda_embed_ed/files/6644017/readme.txt)

**Comment by halfbrained** [comment]
> Shows "included" file in embedded editor, when additional editor UI control is
> shown above the "inter-line gap".

This doesn't sound right, maybe: 
> Shows "included" file in embedded editor - additional editor UI control is
> shown between the text lines.

**Comment by Alexey-T** [comment]
it is OK, your variant

**Comment by halfbrained** [comment]
Thanks, updated
